---
title: "cartograph_notes"
author: "Aleksander Wael"
date: "4/24/2023"
output: html_document
---

```{r}
# Load libraries
'library(dplyr)        # data wrangling
library(cartogram)    # for the cartogram
library(ggplot2)      # to realize the plots
library(broom)        # from geospatial format to data frame
library(tweenr)       # to create transition dataframe between 2 states
library(gganimate)    # To realize the animation
library(maptools)     # world boundaries coordinates
library(viridis)      # for a nice color palette'

# !install.packages('rgeos', type='source')
# !install.packages('rgdal', type='source')

pacman::p_load(dplyr, plyr, cartogram, ggplot2, gganimate, broom, tweenr, gganimate, maptools, viridis, stringi, sf, rgeos, rgdal, mapproj, gifski)
```

```{r}
# Get the shape file of Africa
data(wrld_simpl)
afr=wrld_simpl[wrld_simpl$REGION==2,]

# A basic representation
wrld_simpl@data
```

```{r}
# Prepare municipalities
library(raster)
municipalities <- getData("GADM", country = "DK", level = 2)
```

```{r}
indbygger_data = read.csv2("data/indbygger_data.csv", header = T)
indbygger_data <- na.omit(indbygger_data)

areal_data = read.csv2("data/areal_data.csv", header = T)
```

```{r}
# Changing kommune names for indbygger_data df

indbygger_data$Kommune <- stri_replace_all(indbygger_data$Kommune, "", regex = " Kommune") # Københavns, Vesthimmerlands, Bornholms, AArhus
indbygger_data$Kommune <- stri_replace_all(indbygger_data$Kommune, "København", regex = "Københavns")
indbygger_data$Kommune <- stri_replace_all(indbygger_data$Kommune, "Vesthimmerland", regex = "Vesthimmerlands")
indbygger_data$Kommune <- stri_replace_all(indbygger_data$Kommune, "Bornholm", regex = "Bornholms")
indbygger_data$Kommune <- stri_replace_all(indbygger_data$Kommune, "Århus", regex = "Aarhus")
indbygger_data$Kommune <- stri_replace_all(indbygger_data$Kommune, "", regex = "\\(.*\\)")
indbygger_data$Kommune <- stri_replace_all(indbygger_data$Kommune, "", regex = " ")
indbygger_data$Kommune <- stri_replace_all(indbygger_data$Kommune, "Høje Taastrup", regex = "Høje-Taastrup")
```

```{r}
# Joining DF
# Make into spatial object again
colnames(municipalities@data)[7] <- "Kommune"

municipalities <- subset(municipalities, Kommune != "Christiansø")

municipalities@data <- join(municipalities@data, indbygger_data, by = "Kommune")
```

```{r}
municipalities@data[,15:45] <- municipalities@data[,15:45] %>% 
  mutate_all(as.numeric)
```

```{r}
mun_sf <- st_as_sf(municipalities)
mun_sf <- st_transform(mun_sf, crs = 25832)

municipalities_projected <- as_Spatial(mun_sf)
```

```{r}
dk_cartogram <- cartogram_cont(mun_sf, "X1993", iter = 5)

dk_cartogram_spdf <- as_Spatial(dk_cartogram)
```

```{r}
mun_df <- tidy(municipalities_projected, region = "Kommune") %>% 
  left_join(., municipalities_projected@data, by=c("id"="Kommune"))

cartogram_df <- tidy(dk_cartogram_spdf, region = "Kommune") %>% 
  left_join(., municipalities_projected@data, by=c("id"="Kommune"))

afr_df <- tidy(afr) %>% 
  left_join(., afr@data, by=c("id"="ISO3"))
```

```{r}
# Centers for kommune labels
# Calculate the position of state labels
centers <- cbind.data.frame(data.frame(gCentroid(municipalities_projected, byid=TRUE), id=municipalities_projected$Kommune))
centers_cartogram <- cbind.data.frame(data.frame(gCentroid(dk_cartogram_spdf, byid=TRUE), id=dk_cartogram_spdf$Kommune))

# Add indbygger data to centers
centers_cartogram <- centers_cartogram %>% 
  left_join(mun_df, by="id")
```

```{r}
# Define list of years which have data
years <- names(municipalities[,15:45])

# Loop over each year, create a cartogram and save plot
get_cartograms = function(){
    for (x in years){
    
      x_cartogram <- cartogram_cont(mun_sf, x, iter = 5)
      
      p <- ggplot() +
      geom_sf(data = x_cartogram, aes_string(fill = x), size=0, alpha=0.9)+
      theme_void()+
      scale_fill_viridis(name="Population (thousands)") +
      labs(title = "Denmark", subtitle=paste("Population per kommune in ", x, sep="")) +
      geom_text(data=centers_cartogram, aes_string(x="x", y="y", label=x), color="white", size=3, alpha=1) +
      theme(
        text = element_text(color = "#22211d"), 
        plot.background = element_rect(fill = "#f5f5f4", color = NA), 
        panel.background = element_rect(fill = "#f5f5f4", color = NA), 
        legend.background = element_rect(fill = "#f5f5f4", color = NA),
        plot.title = element_text(size= 22, hjust=0.5, color = "#4e4d47", margin = margin(b = -0.1, t = 0.4, l = 2, unit = "cm")),
        plot.subtitle = element_text(size= 13, hjust=0.5, color = "#4e4d47", margin = margin(b = -0.1, t = 0.4, l = 2, unit = "cm")),
        legend.position = c(0.8, 0.8))
    
    ggsave(plot = p, filename=paste("plot_", x, ".png", sep=""))
  }
}
```

```{r}
# get_cartograms()
```

```{r}
# png_files <- list.files(".", pattern = ".*png$", full.names = TRUE)
# gifski(png_files, gif_file = "animation.gif", width = 2100, height = 2100, delay = 0.1)
```


```{r}
p <- ggplot() +
    geom_sf(data = dk_cartogram, aes_string(fill = "X1993"), size=0, alpha=0.9)+
    theme_void()+
    scale_fill_gradient(name="Population (thousands)", low = "black", high = "#00ffff") +
    labs(title = "Denmark", subtitle=paste("Population per kommune in ", "1993", sep="")) +
    geom_text(data=centers_cartogram, aes_string(x="x", y="y", label= "X1993"), color="black", size=2, alpha=1) +
    theme(
      text = element_text(color = "#22211d"), 
      plot.background = element_rect(fill = "#f5f5f4", color = NA), 
      panel.background = element_rect(fill = "#f5f5f4", color = NA), 
      legend.background = element_rect(fill = "#f5f5f4", color = NA),
      plot.title = element_text(size= 22, hjust=0.5, color = "#4e4d47", margin = margin(b = -0.1, t = 0.4, l = 2, unit = "cm")),
      plot.subtitle = element_text(size= 13, hjust=0.5, color = "#4e4d47", margin = margin(b = -0.1, t = 0.4, l = 2, unit = "cm")),
      legend.position = c(0.8, 0.8))

ggsave(plot = p, filename=paste("plot_just_DK_", "X1993", ".png", sep=""))
```

```{r}
p
```


```{r}
# Subset mun_df to fit
extra_rows <- cartogram_df[194028:195851,]
cartogram_df <- rbind(cartogram_df, extra_rows)

# Give an id to every single point that compose the boundaries
cartogram_df$counter <- seq(1,nrow(cartogram_df))
mun_df$counter <- seq(1,nrow(mun_df))
 
# Bind both map info in a data frame. 3 states: map --> cartogram --> map
data <- rbind(mun_df, cartogram_df, mun_df)
 
# Set transformation type + time
data$ease <- "cubic-in-out"
data$time <- rep(c(1:3), each=nrow(mun_df))
 
# Calculate the transition between these 2 objects?
dt <- tween_elements(data, time='time', group='counter', ease='ease', nframes = 30)
 
# check a few frame
ggplot() + 
  geom_polygon(data = dt %>% filter(.frame==0) %>% arrange(order), 
    aes(fill = X1993, x = long, y = lat, group = group), size=0, alpha=0.9
  )
ggplot() + 
  geom_polygon(data = dt %>% filter(.frame==5) %>% arrange(order), 
    aes(fill = X1993, x = long, y = lat, group = group) , size=0, alpha=0.9
  )
ggplot() + 
  geom_polygon(data = dt %>% filter(.frame==10) %>% arrange(order), 
    aes(fill = X1993, x = long, y = lat, group = group) , size=0, alpha=0.9
  )
```
```{r}
# Give an id to every single point that compose the boundaries
afr_cartogram_df$id <- seq(1,nrow(afr_cartogram_df))
afr_df$id <- seq(1,nrow(afr_df))
 
# Bind both map info in a data frame. 3 states: map --> cartogram --> map
data <- rbind(afr_df, afr_cartogram_df, afr_df)
 
# Set transformation type + time
data$ease <- "cubic-in-out"
data$time <- rep(c(1:3), each=nrow(afr_df))
 
# Calculate the transition between these 2 objects?
dt <- tween_elements(data, time='time', group='id', ease='ease', nframes = 30)
 
# check a few frame
ggplot() + 
  geom_polygon(data = dt %>% filter(.frame==0) %>% arrange(order), 
    aes(fill = POP2005, x = long, y = lat, group = group), size=0, alpha=0.9
  )
ggplot() + 
  geom_polygon(data = dt %>% filter(.frame==5) %>% arrange(order), 
    aes(fill = POP2005, x = long, y = lat, group = group) , size=0, alpha=0.9
  )
ggplot() + 
  geom_polygon(data = dt %>% filter(.frame==10) %>% arrange(order), 
    aes(fill = POP2005, x = long, y = lat, group = group) , size=0, alpha=0.9
  )
```

```{r}
# Make dt a sf object
```















