---
title: "cartograph_notes"
author: "Aleksander Wael"
date: "4/24/2023"
output: html_document
---

```{r}
# Load libraries
'library(dplyr)        # data wrangling
library(cartogram)    # for the cartogram
library(ggplot2)      # to realize the plots
library(broom)        # from geospatial format to data frame
library(tweenr)       # to create transition dataframe between 2 states
library(gganimate)    # To realize the animation
library(maptools)     # world boundaries coordinates
library(viridis)      # for a nice color palette'

# !install.packages('rgeos', type='source')
# !install.packages('rgdal', type='source')

'pacman::p_load(dplyr, plyr, cartogram, ggplot2, gganimate, broom, tweenr, raster, gganimate, maptools, viridis, stringi, sf, rgeos, rgdal, mapproj, gifski, scales)'

pacman::p_load(raster, stringi, plyr, sf, cartogram, tidyverse, viridis, gifski)
```

```{r}
# Prepare municipalities
municipalities <- getData("GADM", country = "DK", level = 2)
```

```{r}
# Import municipality data
indbygger_data = read.csv2("../data/indbygger_data.csv", header = T)

# Omit NAs
indbygger_data <- na.omit(indbygger_data)
```

```{r}
# Changing municipality names to match between data sources
indbygger_data$Kommune <- stri_replace_all(indbygger_data$Kommune, "", regex = " Kommune") # Københavns, Vesthimmerlands, Bornholms, AArhus
indbygger_data$Kommune <- stri_replace_all(indbygger_data$Kommune, "København", regex = "Københavns")
indbygger_data$Kommune <- stri_replace_all(indbygger_data$Kommune, "Vesthimmerland", regex = "Vesthimmerlands")
indbygger_data$Kommune <- stri_replace_all(indbygger_data$Kommune, "Bornholm", regex = "Bornholms")
indbygger_data$Kommune <- stri_replace_all(indbygger_data$Kommune, "Århus", regex = "Aarhus")
indbygger_data$Kommune <- stri_replace_all(indbygger_data$Kommune, "", regex = "\\(.*\\)")
indbygger_data$Kommune <- stri_replace_all(indbygger_data$Kommune, "", regex = " ")
indbygger_data$Kommune <- stri_replace_all(indbygger_data$Kommune, "Høje Taastrup", regex = "Høje-Taastrup")
```

```{r}
# Renaming name column to match between data sources
colnames(municipalities@data)[7] <- "Kommune"

# Remove christiansø kommune due to missing data
municipalities <- subset(municipalities, Kommune != "Christiansø")

# Joining DF
municipalities@data <- join(municipalities@data, indbygger_data, by = "Kommune")
```

```{r}
# Changing all population columns to numeric
municipalities@data[,15:45] <- municipalities@data[,15:45] %>% 
  mutate_all(as.numeric)
```

```{r}
# Project coordinates to CRS 25832
mun_sf <- st_as_sf(municipalities)
mun_sf <- st_transform(mun_sf, crs = 25832)

# Return to SPDF object
municipalities_projected <- as_Spatial(mun_sf)
```

```{r}
# Create cartogram based on 1993 population counts
# dk_cartogram <- cartogram_cont(mun_sf, "X1993", iter = 5)

# Return to SPDF object
# dk_cartogram_spdf <- as_Spatial(dk_cartogram)
```

```{r}
# Tidy to prepare for plotting
# mun_df <- tidy(municipalities_projected, region = "Kommune") %>% 
#   left_join(., municipalities_projected@data, by=c("id"="Kommune"))

# cartogram_df <- tidy(dk_cartogram_spdf, region = "Kommune") %>% 
#   left_join(., municipalities_projected@data, by=c("id"="Kommune"))
```

```{r}
# Centers for municipality labels
# centers <- cbind.data.frame(data.frame(gCentroid(municipalities_projected, byid=TRUE), id=municipalities_projected$Kommune))
# centers_cartogram <- cbind.data.frame(data.frame(gCentroid(dk_cartogram_spdf, byid=TRUE), id=dk_cartogram_spdf$Kommune))

# Add population data to centers
# centers_cartogram <- centers_cartogram %>% 
#   left_join(mun_df, by="id")
```

```{r}
# Plot a normal choropleth 
p <- ggplot() +
    geom_sf(data = mun_sf, aes(fill = X2023), size=0, alpha=0.9)+
    theme_void()+
    scale_fill_viridis(name="Population (thousands)", option = "B") +
    labs(title = "Choropleth map of Danish municipalities", subtitle=paste("Population per municipality in ", "2023", sep="")) +
#    geom_text(data=centers_cartogram, aes_string(x="x", y="y", label= "X1993"), color="black", size=2, alpha=1) +
    theme(
      text = element_text(color = "#22211d"), 
      plot.background = element_rect(fill = "#f5f5f4", color = NA), 
      panel.background = element_rect(fill = "#f5f5f4", color = NA), 
      legend.background = element_rect(fill = "#f5f5f4", color = NA),
      plot.title = element_text(size= 22, hjust=0.5, color = "#4e4d47", margin = margin(b = -0.1, t = 0.4, l = 2, unit = "cm")),
      plot.subtitle = element_text(size= 13, hjust=0.5, color = "#4e4d47", margin = margin(b = -0.1, t = 0.4, l = 2, unit = "cm")),
      legend.position = c(0.8, 0.8))

p

# Save cartogram
# ggsave(path = "../out", plot = p, filename=paste("choropleth_", "X2023", ".png", sep=""), units = "px", width = 2100, height = 2100)
```

```{r}
# Define list of years which have data
years <- names(municipalities[,15:45])

# FUNCTION FOR CREATING 30 CARTOGRAMS
# Loop over each year, create a cartogram and save plot
get_cartograms = function(){
    for (x in years){
    
      x_cartogram <- cartogram_cont(mun_sf, x, iter = 5)
      
      p <- ggplot() +
      geom_sf(data = x_cartogram, aes_string(fill = x), size=0, alpha=0.9)+
      theme_void()+
      scale_fill_viridis(name="Population (thousands)", option = "B") +
      labs(title = "Cartogram/Choropleth map of Danish municipalities", subtitle=paste("Population per municipality in ", x, sep="")) +
#      geom_text(data=centers_cartogram, aes_string(x="x", y="y", label=x), color="white", size=3, alpha=1) + # GET RAW COUNTS FOR EACH MUNICIPALITY
      theme(
        text = element_text(color = "#22211d"), 
        plot.background = element_rect(fill = "#f5f5f4", color = NA), 
        panel.background = element_rect(fill = "#f5f5f4", color = NA), 
        legend.background = element_rect(fill = "#f5f5f4", color = NA),
        plot.title = element_text(size= 22, hjust=0.5, color = "#4e4d47", margin = margin(b = -0.1, t = 0.4, l = 2, unit = "cm")),
        plot.subtitle = element_text(size= 13, hjust=0.5, color = "#4e4d47", margin = margin(b = -0.1, t = 0.4, l = 2, unit = "cm")),
        legend.position = c(0.8, 0.8))
    
    ggsave(path = "../out", plot = p, filename=paste("plot_", x, ".png", sep=""), units = "px", width = 2100, height = 2100)
  }
}
```

```{r}
# Run function
# get_cartograms()
```

```{r}
# Save GIF
# png_files <- list.files("out/", pattern = "plot*.*png$", full.names = TRUE)
# gifski(png_files, gif_file = "../out/animation.gif", width = 2100, height = 2100, delay = 0.15)
```
